// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA10X6ATB7jltHuMQe9PEIxmn6CYDZ_788',
    appId: '1:91296298912:web:0bf4377cdd79535aa0d6c5',
    messagingSenderId: '91296298912',
    projectId: 'reward-sale-app-flutter-app',
    authDomain: 'reward-sale-app-flutter-app.firebaseapp.com',
    storageBucket: 'reward-sale-app-flutter-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVzJcNBufnF25E83zg_RWnKjwgsd7Ls1Q',
    appId: '1:91296298912:android:59f6497ccd114a7ca0d6c5',
    messagingSenderId: '91296298912',
    projectId: 'reward-sale-app-flutter-app',
    storageBucket: 'reward-sale-app-flutter-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLy9o7uNEuxAEmpe8pF8I6DB6tJ4CBo7g',
    appId: '1:91296298912:ios:0694f1a325e2b7b3a0d6c5',
    messagingSenderId: '91296298912',
    projectId: 'reward-sale-app-flutter-app',
    storageBucket: 'reward-sale-app-flutter-app.appspot.com',
    iosBundleId: 'com.sale.spotter.rewardingSaleAppFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLy9o7uNEuxAEmpe8pF8I6DB6tJ4CBo7g',
    appId: '1:91296298912:ios:5bb8b8a9ae4b440ba0d6c5',
    messagingSenderId: '91296298912',
    projectId: 'reward-sale-app-flutter-app',
    storageBucket: 'reward-sale-app-flutter-app.appspot.com',
    iosBundleId: 'com.sale.spotter.rewardingSaleAppFlutterApp.RunnerTests',
  );
}